# Generated by Django 5.1.2 on 2024-10-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ubicacion",
            options={"verbose_name_plural": "Ubicaciones"},
        ),
        migrations.AddField(
            model_name="ubicacion",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ubicacion",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hijos",
                to="gestion.ubicacion",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="articulos/"),
        ),
    ]
