# Generated by Django 5.1.2 on 2024-10-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0002_alter_ubicacion_options_ubicacion_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="categorias",
            field=models.ManyToManyField(blank=True, to="gestion.categoria"),
        ),
        migrations.AddField(
            model_name="categoria",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
